# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Uber API
  description: Move your app forward with the Uber API
  version: "1.0.0"
# array of all schemes that your API supports
schemes:
  - http
produces:
  - application/json
paths:
  /people:
    get:
      responses:
        200:
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
  /people/add/{data}:
    get:
      parameters:
        - name: data
          in: path
          required: true
          type: string
      responses:
        '200':
          description: ""

definitions:
  Person:
    type: object
    properties:
      name:
        type: string
        